version: "3.3"
services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - jaayedaad-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

volumes:
  jaayedaad-db:
    driver: local